/*
 * Auto-generated WebFast Application
 * Generated by WebFast Compiler
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>
#include "webfast_runtime.h"

// Configuration
typedef struct {
    int port;
} Config;

Config config;

// Route Handlers
static Response* route_handler_0(Request* req) {
    return webfast_json_response({.message = "Hello from WebFast!"});
}

int main(int argc, char** argv) {
    printf("Starting WebFast Application...
");

    // Initialize configuration
    config.port = 8000;

    // Register routes
    webfast_register_route("GET", "/", route_handler_0);

    // Start server
    int port = config.port;
    printf("Server running on http://localhost:%d
", port);
    webfast_run(port);

    return 0;
}
