/* Auto-generated by WebFast v5.0 */

#include "webfast_runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    long port;
    const char* site_name;
    const char* site_url;
    const char* author;
    const char* version;
    const char* environment;
} Config;

static Config config;

static SeoMetadata* current_seo = NULL;
const SeoMetadata* webfast_get_seo(void) { return current_seo; }

/* Route handlers */
static Response* route_handler_0(Request* req) {
    JsonBuilder jb_0;
    jb_init(&jb_0);
    jb_start_object(&jb_0);
        {
        jb_key(&jb_0, "simple_array");
        jb_start_array(&jb_0);
            jb_arr_int(&jb_0, 1);
            jb_arr_int(&jb_0, 2);
            jb_arr_int(&jb_0, 3);
            jb_arr_int(&jb_0, 4);
            jb_arr_int(&jb_0, 5);
        jb_end_array(&jb_0);
    }
        {
        jb_key(&jb_0, "string_array");
        jb_start_array(&jb_0);
            jb_arr_string(&jb_0, "hello");
            jb_arr_string(&jb_0, "world");
            jb_arr_string(&jb_0, "webfast");
        jb_end_array(&jb_0);
    }
        {
        jb_key(&jb_0, "mixed_array");
        jb_start_array(&jb_0);
            jb_arr_int(&jb_0, 1);
            jb_arr_string(&jb_0, "two");
            jb_arr_bool(&jb_0, true);
            jb_arr_null(&jb_0);
            jb_arr_float(&jb_0, 3.140000);
        jb_end_array(&jb_0);
    }
        {
        jb_key(&jb_0, "empty_array");
        jb_start_array(&jb_0);
        jb_end_array(&jb_0);
    }
        {
        jb_key(&jb_0, "nested_objects");
        jb_start_array(&jb_0);
            jb_arr_start_object(&jb_0);
                jb_add_int(&jb_0, "id", 1);
                jb_add_string(&jb_0, "name", "Alice");
                jb_add_bool(&jb_0, "active", true);
            jb_end_object(&jb_0);
            jb_arr_start_object(&jb_0);
                jb_add_int(&jb_0, "id", 2);
                jb_add_string(&jb_0, "name", "Bob");
                jb_add_bool(&jb_0, "active", false);
            jb_end_object(&jb_0);
            jb_arr_start_object(&jb_0);
                jb_add_int(&jb_0, "id", 3);
                jb_add_string(&jb_0, "name", "Charlie");
                jb_add_bool(&jb_0, "active", true);
            jb_end_object(&jb_0);
        jb_end_array(&jb_0);
    }
    jb_end_object(&jb_0);
    Response* resp = webfast_json_response(jb_get(&jb_0));
    jb_free(&jb_0);
    return resp;
}

static Response* route_handler_1(Request* req) {
    JsonBuilder jb_1;
    jb_init(&jb_1);
    jb_start_object(&jb_1);
        {
        jb_key(&jb_1, "users");
        jb_start_array(&jb_1);
            jb_arr_start_object(&jb_1);
                jb_add_int(&jb_1, "id", 1);
                jb_add_string(&jb_1, "name", "Alice");
                jb_add_string(&jb_1, "email", "alice@example.com");
                                {
                    jb_key(&jb_1, "profile");
                    jb_start_object(&jb_1);
                        jb_add_int(&jb_1, "age", 30);
                        jb_add_string(&jb_1, "city", "Tehran");
                    jb_end_object(&jb_1);
                }
            jb_end_object(&jb_1);
            jb_arr_start_object(&jb_1);
                jb_add_int(&jb_1, "id", 2);
                jb_add_string(&jb_1, "name", "Bob");
                jb_add_string(&jb_1, "email", "bob@example.com");
                                {
                    jb_key(&jb_1, "profile");
                    jb_start_object(&jb_1);
                        jb_add_int(&jb_1, "age", 25);
                        jb_add_string(&jb_1, "city", "Isfahan");
                    jb_end_object(&jb_1);
                }
            jb_end_object(&jb_1);
        jb_end_array(&jb_1);
    }
        {
        jb_key(&jb_1, "metadata");
        jb_start_object(&jb_1);
            jb_add_int(&jb_1, "total", 2);
            jb_add_int(&jb_1, "page", 1);
        jb_end_object(&jb_1);
    }
    jb_end_object(&jb_1);
    Response* resp = webfast_json_response(jb_get(&jb_1));
    jb_free(&jb_1);
    return resp;
}

static Response* route_handler_2(Request* req) {
    SeoMetadata seo_2 = {0};
    seo_2.title = "WebFast v5.0 - Production Ready";
    seo_2.description = "All critical issues fixed";
    seo_2.keywords = "webfast, production, secure";
    seo_2.og_title = "WebFast v5.0";
    seo_2.og_type = "website";
    return webfast_render_html_with_seo("<h1>SEO Test Page</h1><p>All features working!</p>", webfast_get_seo());
}

static Response* route_handler_3(Request* req) {
    const char* id = webfast_get_param(req, "id");
    JsonBuilder jb_3;
    jb_init(&jb_3);
    jb_start_object(&jb_3);
    jb_add_string(&jb_3, "user_id", id);
    jb_add_string(&jb_3, "name", "User");
    jb_add_bool(&jb_3, "active", true);
    jb_add_timestamp(&jb_3, "created_at");
    jb_end_object(&jb_3);
    Response* resp = webfast_json_response(jb_get(&jb_3));
    jb_free(&jb_3);
    return resp;
}

static Response* route_handler_4(Request* req) {
    const char* postId = webfast_get_param(req, "postId");
    const char* commentId = webfast_get_param(req, "commentId");
    JsonBuilder jb_4;
    jb_init(&jb_4);
    jb_start_object(&jb_4);
    jb_add_string(&jb_4, "post_id", postId);
    jb_add_string(&jb_4, "comment_id", commentId);
    jb_add_timestamp(&jb_4, "timestamp");
    jb_end_object(&jb_4);
    Response* resp = webfast_json_response(jb_get(&jb_4));
    jb_free(&jb_4);
    return resp;
}

static Response* route_handler_5(Request* req) {
    JsonBuilder jb_5;
    jb_init(&jb_5);
    jb_start_object(&jb_5);
    jb_add_string(&jb_5, "message", "Query string parsing works");
    jb_add_string(&jb_5, "note", "No memory leaks - static buffer used");
        {
        jb_key(&jb_5, "results");
        jb_start_array(&jb_5);
            jb_arr_start_object(&jb_5);
                jb_add_int(&jb_5, "id", 1);
                jb_add_string(&jb_5, "title", "Result 1");
            jb_end_object(&jb_5);
            jb_arr_start_object(&jb_5);
                jb_add_int(&jb_5, "id", 2);
                jb_add_string(&jb_5, "title", "Result 2");
            jb_end_object(&jb_5);
        jb_end_array(&jb_5);
    }
    jb_end_object(&jb_5);
    Response* resp = webfast_json_response(jb_get(&jb_5));
    jb_free(&jb_5);
    return resp;
}

static Response* route_handler_6(Request* req) {
    JsonBuilder jb_6;
    jb_init(&jb_6);
    jb_start_object(&jb_6);
    jb_add_string(&jb_6, "status", "created");
    jb_add_string(&jb_6, "method", "POST");
    jb_add_timestamp(&jb_6, "timestamp");
    jb_add_string(&jb_6, "note", "POST body parsing with Content-Length is working");
    jb_end_object(&jb_6);
    Response* resp = webfast_json_response(jb_get(&jb_6));
    jb_free(&jb_6);
    return resp;
}

static Response* route_handler_7(Request* req) {
    JsonBuilder jb_7;
    jb_init(&jb_7);
    jb_start_object(&jb_7);
    jb_add_string(&jb_7, "string", "hello world");
    jb_add_int(&jb_7, "integer", 42);
    jb_add_float(&jb_7, "float", 3.141590);
    jb_add_bool(&jb_7, "boolean_true", true);
    jb_add_bool(&jb_7, "boolean_false", false);
    jb_add_null(&jb_7, "null_value");
    jb_add_timestamp(&jb_7, "timestamp");
        {
        jb_key(&jb_7, "array");
        jb_start_array(&jb_7);
            jb_arr_int(&jb_7, 1);
            jb_arr_int(&jb_7, 2);
            jb_arr_int(&jb_7, 3);
        jb_end_array(&jb_7);
    }
        {
        jb_key(&jb_7, "object");
        jb_start_object(&jb_7);
                        {
                jb_key(&jb_7, "nested");
                jb_start_object(&jb_7);
                                        {
                        jb_key(&jb_7, "deep");
                        jb_start_object(&jb_7);
                            jb_add_string(&jb_7, "value", "works!");
                        jb_end_object(&jb_7);
                    }
                jb_end_object(&jb_7);
            }
        jb_end_object(&jb_7);
    }
    jb_end_object(&jb_7);
    Response* resp = webfast_json_response(jb_get(&jb_7));
    jb_free(&jb_7);
    return resp;
}

static Response* route_handler_8(Request* req) {
    JsonBuilder jb_8;
    jb_init(&jb_8);
    jb_start_object(&jb_8);
    jb_add_string(&jb_8, "site_name", config.site_name);
    jb_add_string(&jb_8, "site_url", config.site_url);
    jb_add_string(&jb_8, "author", config.author);
    jb_add_string(&jb_8, "version", config.version);
    jb_add_string(&jb_8, "environment", config.environment);
    jb_add_int(&jb_8, "port", config.port);
    jb_end_object(&jb_8);
    Response* resp = webfast_json_response(jb_get(&jb_8));
    jb_free(&jb_8);
    return resp;
}

static Response* route_handler_9(Request* req) {
    return webfast_text_response("User-agent: *\\nAllow: /\\n");
}

static Response* route_handler_10(Request* req) {
    const char* id = webfast_get_param(req, "id");
    JsonBuilder jb_9;
    jb_init(&jb_9);
    jb_start_object(&jb_9);
    jb_add_string(&jb_9, "status", "updated");
    jb_add_string(&jb_9, "method", "PUT");
    jb_add_string(&jb_9, "id", id);
    jb_add_timestamp(&jb_9, "timestamp");
    jb_end_object(&jb_9);
    Response* resp = webfast_json_response(jb_get(&jb_9));
    jb_free(&jb_9);
    return resp;
}

static Response* route_handler_11(Request* req) {
    const char* id = webfast_get_param(req, "id");
    JsonBuilder jb_10;
    jb_init(&jb_10);
    jb_start_object(&jb_10);
    jb_add_string(&jb_10, "status", "deleted");
    jb_add_string(&jb_10, "method", "DELETE");
    jb_add_string(&jb_10, "id", id);
    jb_add_timestamp(&jb_10, "timestamp");
    jb_end_object(&jb_10);
    Response* resp = webfast_json_response(jb_get(&jb_10));
    jb_free(&jb_10);
    return resp;
}

static Response* route_handler_12(Request* req) {
    JsonBuilder jb_11;
    jb_init(&jb_11);
    jb_start_object(&jb_11);
    jb_add_string(&jb_11, "status", "healthy");
    jb_add_string(&jb_11, "version", config.version);
    jb_add_timestamp(&jb_11, "uptime");
        {
        jb_key(&jb_11, "checks");
        jb_start_object(&jb_11);
            jb_add_string(&jb_11, "database", "ok");
            jb_add_string(&jb_11, "cache", "ok");
            jb_add_string(&jb_11, "memory", "ok");
        jb_end_object(&jb_11);
    }
    jb_end_object(&jb_11);
    Response* resp = webfast_json_response(jb_get(&jb_11));
    jb_free(&jb_11);
    return resp;
}

static Response* route_handler_13(Request* req) {
    JsonBuilder jb_12;
    jb_init(&jb_12);
    jb_start_object(&jb_12);
        {
        jb_key(&jb_12, "overview");
        jb_start_object(&jb_12);
            jb_add_int(&jb_12, "total_users", 1234);
            jb_add_int(&jb_12, "active_sessions", 567);
            jb_add_float(&jb_12, "revenue", 9876.540000);
        jb_end_object(&jb_12);
    }
        {
        jb_key(&jb_12, "recent_activity");
        jb_start_array(&jb_12);
            jb_arr_start_object(&jb_12);
                jb_add_string(&jb_12, "user", "Alice");
                jb_add_string(&jb_12, "action", "login");
            jb_end_object(&jb_12);
            jb_arr_start_object(&jb_12);
                jb_add_string(&jb_12, "user", "Bob");
                jb_add_string(&jb_12, "action", "purchase");
            jb_end_object(&jb_12);
        jb_end_array(&jb_12);
    }
        {
        jb_key(&jb_12, "stats");
        jb_start_object(&jb_12);
                        {
                jb_key(&jb_12, "daily_visits");
                jb_start_array(&jb_12);
                    jb_arr_int(&jb_12, 100);
                    jb_arr_int(&jb_12, 150);
                    jb_arr_int(&jb_12, 200);
                    jb_arr_int(&jb_12, 180);
                    jb_arr_int(&jb_12, 220);
                jb_end_array(&jb_12);
            }
            jb_add_int(&jb_12, "weekly_average", 170);
        jb_end_object(&jb_12);
    }
    jb_end_object(&jb_12);
    Response* resp = webfast_json_response(jb_get(&jb_12));
    jb_free(&jb_12);
    return resp;
}

static Response* route_handler_14(Request* req) {
    SeoMetadata seo_13 = {0};
    seo_13.title = "About WebFast v5.0";
    seo_13.description = "Production-ready web framework";
    seo_13.og_title = "About WebFast";
    JsonBuilder jb_14;
    jb_init(&jb_14);
    jb_start_object(&jb_14);
    jb_add_string(&jb_14, "name", config.site_name);
    jb_add_string(&jb_14, "version", config.version);
        {
        jb_key(&jb_14, "features");
        jb_start_array(&jb_14);
            jb_arr_string(&jb_14, "Dynamic Memory");
            jb_arr_string(&jb_14, "Thread-Safe");
            jb_arr_string(&jb_14, "No Memory Leaks");
            jb_arr_string(&jb_14, "Keep-Alive");
            jb_arr_string(&jb_14, "Secure UUID");
        jb_end_array(&jb_14);
    }
    jb_end_object(&jb_14);
    Response* resp = webfast_json_response(jb_get(&jb_14));
    jb_free(&jb_14);
    return resp;
}

static Response* route_handler_15(Request* req) {
    JsonBuilder jb_15;
    jb_init(&jb_15);
    jb_start_object(&jb_15);
    jb_add_string(&jb_15, "message", "Secure UUID generation");
    jb_add_timestamp(&jb_15, "timestamp");
    jb_add_string(&jb_15, "note", "UUIDs use /dev/urandom for security");
    jb_end_object(&jb_15);
    Response* resp = webfast_json_response(jb_get(&jb_15));
    jb_free(&jb_15);
    return resp;
}

static Response* route_handler_16(Request* req) {
    SeoMetadata seo_16 = {0};
    seo_16.title = "WebFast v5.0 - Production Ready";
    seo_16.description = "All 10 critical issues fixed";
    seo_16.og_title = "WebFast v5.0";
    JsonBuilder jb_17;
    jb_init(&jb_17);
    jb_start_object(&jb_17);
    jb_add_string(&jb_17, "message", "Welcome to WebFast v5.0!");
    jb_add_string(&jb_17, "version", config.version);
    jb_add_string(&jb_17, "site", config.site_name);
    jb_add_timestamp(&jb_17, "timestamp");
        {
        jb_key(&jb_17, "features");
        jb_start_array(&jb_17);
            jb_arr_string(&jb_17, "Arrays in JSON");
            jb_arr_string(&jb_17, "Nested Objects");
            jb_arr_string(&jb_17, "SEO to HTML");
            jb_arr_string(&jb_17, "Route Parameters");
            jb_arr_string(&jb_17, "Query Strings");
            jb_arr_string(&jb_17, "POST Body Parsing");
            jb_arr_string(&jb_17, "Keep-Alive");
            jb_arr_string(&jb_17, "Numeric Timestamps");
            jb_arr_string(&jb_17, "Secure UUID");
            jb_arr_string(&jb_17, "All HTTP Methods");
        jb_end_array(&jb_17);
    }
        {
        jb_key(&jb_17, "stats");
        jb_start_object(&jb_17);
            jb_add_int(&jb_17, "routes", 14);
                        {
                jb_key(&jb_17, "methods");
                jb_start_array(&jb_17);
                    jb_arr_string(&jb_17, "GET");
                    jb_arr_string(&jb_17, "POST");
                    jb_arr_string(&jb_17, "PUT");
                    jb_arr_string(&jb_17, "DELETE");
                jb_end_array(&jb_17);
            }
            jb_add_int(&jb_17, "critical_issues_fixed", 10);
        jb_end_object(&jb_17);
    }
    jb_end_object(&jb_17);
    Response* resp = webfast_json_response(jb_get(&jb_17));
    jb_free(&jb_17);
    return resp;
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;

    config.port = 8000;
    config.site_name = "WebFast v5.0 Production";
    config.site_url = "http://localhost:8000";
    config.author = "WebFast Team";
    config.version = "5.0.0";
    config.environment = "production";

    webfast_register_route("GET", "/test/arrays", route_handler_0);
    webfast_register_route("GET", "/test/nested", route_handler_1);
    webfast_register_route("GET", "/test/seo", route_handler_2);
    webfast_register_route("GET", "/user/{id}", route_handler_3);
    webfast_register_route("GET", "/post/{postId}/comment/{commentId}", route_handler_4);
    webfast_register_route("GET", "/search", route_handler_5);
    webfast_register_route("POST", "/api/create", route_handler_6);
    webfast_register_route("GET", "/test/types", route_handler_7);
    webfast_register_route("GET", "/test/config", route_handler_8);
    webfast_register_route("GET", "/robots.txt", route_handler_9);
    webfast_register_route("PUT", "/api/update/{id}", route_handler_10);
    webfast_register_route("DELETE", "/api/delete/{id}", route_handler_11);
    webfast_register_route("GET", "/health", route_handler_12);
    webfast_register_route("GET", "/api/dashboard", route_handler_13);
    webfast_register_route("GET", "/about", route_handler_14);
    webfast_register_route("GET", "/test/uuid", route_handler_15);
    webfast_register_route("GET", "/", route_handler_16);

    webfast_run(8000);
    return 0;
}
